### ISSUE TITLE
🚀 Будущие планы и расширения

### ISSUE THREAD

**Issue by AlexH73** [AlexH73/cohortCinema#15]
Вот примерный план «на будущее» для расширения проекта Cinema

---

### 1. Front-end (интерфейс пользователя)

> Сейчас у нас чисто консольное приложение. Далее можно выбрать один из путей:

- **1.1. Web-REST API + SPA**  
  - Реализовать REST-контроллеры на Spring Boot (`@RestController`) для всех основных сущностей (User, Film, Hall, Session, Ticket, Order, Product, Report).  
  - Сделать Single-Page Application (React / Vue / Angular) для клиентов и админов:
    - Клиентская часть: поиск фильмов, бронирование, покупки, история.
    - Админка: CRUD-операции, отчёты, управление пользователями.
  - Аутентификация JWT + ролевой доступ.

- **1.2. Web-сервер с серверной отрисовкой (Thymeleaf)**  
  - Использовать Spring MVC + Thymeleaf:  
    - HTML-страницы для каждого меню и формы.  
    - Поддержка Bootstrap для адаптивности.  
    - Страничная навигация, валидированиe на сервере и в JS.

- **1.3. Desktop-GUI**  
  - JavaFX или Swing-клиент, который подключается по REST к бэкенду.

---

### 2. Unit-тесты и покрытие

- **Цель:** минимум **80%** покрытия для бизнес-логики (`service`-слой).  
- **Инструменты:**  
  - JUnit 5  
  - Mockito / MockK для мокирования репозиториев  
  - AssertJ для удобных ассерт —ов  
- **Что тестировать:**  
  - Сервисные методы: создание/поиск/изменение/удаление во всех модулях (User, Film, Hall, Session, Ticket, Order, Product, Report).  
  - Граничные и негативные сценарии: неверный ввод, повторные оплаты, пересечения сеансов и т.д.

---

### 3. База данных & Docker

- **Выбор СУБД:** PostgreSQL (рекомендуется для продуктивных систем).  
- **Docker Compose** для локального развёртывания:  
  ```yaml
  version: '3.8'
  
  services:
    db:
      image: postgres:15
      environment:
        POSTGRES_DB: cinema
        POSTGRES_USER: cinema_user
        POSTGRES_PASSWORD: cinema_pass
      ports:
        - "5432:5432"
      volumes:
        - db_data:/var/lib/postgresql/data
  
    app:
      build: .
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cinema
        SPRING_DATASOURCE_USERNAME: cinema_user
        SPRING_DATASOURCE_PASSWORD: cinema_pass
      depends_on:
        - db
  
  volumes:
    db_data:
  ```
- **Конфигурация Spring Boot:**  
  - `spring.jpa.hibernate.ddl-auto=update` (для разработки)  
  - Профили `dev`/`prod`, переключение DDL-стратегии

---

### 4. CI/CD (GitHub Actions)

> Можем добавить чуть позже, когда будет стабильно и нужны автотесты

- **Основной workflow (`.github/workflows/ci.yml`):**
  1. Checkout кода  
  2. Запуск Docker Compose (СУБД)  
  3. Сборка и тесты: `./mvnw clean verify`  
  4. Отчёт покрытия (Jacoco)  
- **Дополнительно:**  
  - Деплой на staging/production (Heroku, AWS Elastic Beanstalk или Docker Hub + VPS)  
  - Автоматическая проверка PR: линтер, форматирование, SonarQube
